/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libapp;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;

import javax.swing.Box;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JColorChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        JMenuBar menuBar = new JMenuBar();
		JMenu menuPlik = new JMenu ("Plik");
		
		JMenuItem mWyjscie = new JMenuItem ("Wyjscie");
		mWyjscie.setAccelerator(KeyStroke.getKeyStroke("ctrl X"));
		mWyjscie.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				int odp = JOptionPane.showConfirmDialog(null, "Czy na pewno wyjsc?", "", JOptionPane.YES_NO_OPTION);
				
				if (odp == JOptionPane.YES_OPTION)
					dispose();
				
				else if (odp == JOptionPane.NO_OPTION || odp == JOptionPane.CLOSED_OPTION)
					JOptionPane.showMessageDialog(null, "Wiedzialem! ;)","", JOptionPane.WARNING_MESSAGE);
		
			}
		});
		menuPlik.add(mWyjscie);
		menuBar.add(menuPlik);
		
		JMenu menuOpcje = new JMenu ("Opcje");
		
		JCheckBoxMenuItem mResizable = new JCheckBoxMenuItem ("Rozszerzalne okno");
		mResizable.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if(mResizable.isSelected())
					setResizable(true);
				else
					setResizable(false);
			}
		});
		
		mResizable.setSelected(true);

		JMenuItem mUstawieniaKolorow = new JMenuItem ("Kolor tla");
		mUstawieniaKolorow.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				Color color = JColorChooser.showDialog(null, "Wybor koloru", Color.GREEN);
				jPanel1.setBackground(color);
				jPanel2.setBackground(color);
			}
		});
		
		menuOpcje.add(mResizable);
		menuOpcje.add(mUstawieniaKolorow);
		menuBar.add(menuOpcje);
		
		JMenu menuPomoc = new JMenu ("Pomoc");
		JMenuItem mOProgramie = new JMenuItem("O programie");
		mOProgramie.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				JOptionPane.showMessageDialog(null, "Program demonstruje rzut balistyczny ciala o stalej masie pod zadanym katem i dana predkoscia. \n\nWykonanie: \nJakub Slowikowski, \nAdam Wierzbinski", "Informacja", JOptionPane.INFORMATION_MESSAGE);
			}
		});
		menuPomoc.add(mOProgramie);
		menuBar.add(Box.createHorizontalGlue());
		menuBar.add(menuPomoc);
		
		setJMenuBar(menuBar);
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        
		
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Krzywa balistyczna");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Font fontPlain = new Font("Courier", Font.PLAIN, 17);
        Font fontBold = new Font("Courier", Font.BOLD, 17);

        jTextField1.setFont(fontPlain);
        jTextField1.setText("10");
        jTextField1.setAutoscrolls(false);
        jTextField1.setToolTipText("Pole do wprowadzanie kata, pod jakim bedzie wykonany rzut");

        jTextField2.setFont(fontPlain);
        jTextField2.setText("10");
        jTextField2.setAutoscrolls(false);
        jTextField2.setToolTipText("Pole do wprowadzania predkosci poczatkowej");

        jButton1.setFont(fontBold);
        jButton1.setText("Rysuj");
        jButton1.setToolTipText("Rysuje wykres toru rzutu o podanych parametrach");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawDisplay(evt);
            }
        });

        jButton2.setFont(fontBold);
        jButton2.setText("Czysc");
        jButton2.setToolTipText("Czysci panel z wykresem i pola do wpisywania");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanDisplay(evt);
            }
        });

        jLabel1.setText("Kat");

        jLabel2.setText("Predkosc");

        jLabel3.setText("[deg]");

        jLabel4.setText("[m/s]");

        jLabel5.setFont(fontBold);
        jLabel5.setText("");

        jLabel6.setFont(fontBold);
        jLabel6.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>      

    private void drawDisplay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawDisplay
    	jLabel5.setText("");  
        jLabel6.setText("");
    	
    	try {
			Dane.kat = Double.parseDouble(jTextField1.getText());
			Dane.predkosc = Double.parseDouble(jTextField2.getText());
			
			if(Dane.kat <= 0 || Dane.kat >=90) {
		        jLabel5.setForeground(Color.red);	        
		        jLabel5.setText(message[0]);
		        
		        jLabel6.setForeground(Color.red);
				jLabel6.setText(message[1]);
				JOptionPane.showMessageDialog(null, message[0],"", JOptionPane.ERROR_MESSAGE);
				throw new NumberFormatException();
				
			}
			
			if(Dane.predkosc <= 0 || Dane.predkosc >= (int) 3*Math.pow(10, 8)) {
		        jLabel5.setForeground(Color.red);
				jLabel5.setText(message[2]);
				
		        jLabel6.setForeground(Color.red);
				jLabel6.setText(message[3]);
				JOptionPane.showMessageDialog(null, message[2],"", JOptionPane.ERROR_MESSAGE);
				throw new NumberFormatException();
			}
			String str1 = NumberFormat.getInstance().format(Dane.zasieg);

			jPanel1.removeAll();
			jPanel1.setLayout(new BorderLayout());
			JPanel dp = DrawPanel.createWoPanel();
			jPanel1.add(dp, BorderLayout.CENTER);
			jPanel1.validate();
			jLabel5.setForeground(Color.BLACK);
			jLabel5.setText("Zasieg rzutu : ");
			jLabel6.setForeground(Color.BLACK);
            jLabel6.setText(Double.toString(Dane.calculate()) + " [m]");
		} catch (NumberFormatException e) {
			e.printStackTrace();
		}
    	
    	
    	
    	
    }//GEN-LAST:event_drawDisplay

    private void cleanDisplay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanDisplay
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        jTextField1.setText("0");
        jTextField2.setText("0");
        jLabel5.setText("");  
        jLabel6.setText("");
    }//GEN-LAST:event_cleanDisplay

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private String[] message = {"Nieprawidlowy kat!",
            "Powinien miescic sie pomiedzy 0 i 90 stopni",
            "Nieprawidlowa predkosc!",
            "Powinna miescic sie miedzy 0 i 10^8"};
            
    // End of variables declaration//GEN-END:variables
}